### ISSUE TITLE
Adding a full-featured png icon

### ISSUE THREAD

**Issue by marmistrz** [yhara/down#3]
I'll be packaging the app for Debian. For this I need icons. 

Could you please add an svg icon to the repo? Alternatively, a high resolution (256x256) png would be ok.

**Comment by yhara** [comment]
Added 256x256 `icon.png`. Let me know if it does not work.

**Comment by marmistrz** [comment]
The new icon is different from the old one (is this on purpose or is it a mistake?) 
Besides, it isn't very symmetric.

Will it be used by the program during runtime? (if not, I'll keep it separate in packaging)

**Comment by yhara** [comment]
Oh I forgot down.exe has an icon. Replaced icon.png in 0e93a87.

> Will it be used by the program during runtime?

No.

**Comment by marmistrz** [comment]
Thanks ;)

The new icon doesn't look very pretty in small menus, e.g. in Cinnamon, see screenshot. Guess the little man is too thin.

![screenshot from 2015-09-11 10 35 21](https://cloud.githubusercontent.com/assets/2914938/9810439/177c5bba-5871-11e5-83a6-b54206910680.png)
