### ISSUE TITLE
Down should support saves in the home folder.

### ISSUE THREAD

**Issue by marmistrz** [yhara/down#4]
I created a Debian package from down. It is installed into /usr/share/games/down. This folder is owned by root and an ordinary user cannot change anything here.

Usually games store their high scores in `$HOME`, for example SuperTuxKart has them in `~/.config/supertuxkart` and hedgewars in `~/.hedgewars`. 

This issue is a major blocker for debianization.

**Comment by yhara** [comment]
Sorry for late response.

Now you can pass `--savefile` option to change the path of the savefile. eg:

`$ ruby ~/somewhere/down.rb --savefile ~/.down.dat`
