### ISSUE TITLE
The --savefile option doesn't create a new directory

### ISSUE THREAD

**Issue by marmistrz** [yhara/down#6]
It may be wise that the game create a directory where the config should reside if it doesn't exist.

```
Savefile: /home/marcin/.config/down/down.dat
/usr/share/games/down/main.rb:45:in `initialize': No such file or directory - /home/marcin/.config/down/down.dat (Errno::ENOENT)
	from /usr/share/games/down/main.rb:45:in `open'
	from /usr/share/games/down/main.rb:45:in `write'
	from /usr/share/games/down/main.rb:153:in `start'
	from /usr/share/games/down/down.rb:30:in `<main>'
```

Besides, since the settings are kept in down.dat too, it may be a good idea to rename `--savefile` to `--config`. May be more intuitive. But it's just a design decision, which is up to you.

**Comment by yhara** [comment]
I like the current behavior because when I mistype the path, error is raised rather than new directory is created in a wrong place. 
But we should raise error before game is started. Thanks for reporting.

**Comment by marmistrz** [comment]
Ok, closing then
